### ISSUE TITLE
Error when run hue useradmin_sync_with_unix

### ISSUE THREAD

**Issue by franksam007** [franksam007/SEBC#8]
Error when run hue useradmin_sync_with_unix
===
Script reports Error: 
<pre>Error: Password not present
Traceback (most recent call last):
  File "./hue", line 12, in <module>
    load_entry_point('desktop==3.9.0', 'console_scripts', 'hue')()
  File "/opt/cloudera/parcels/CDH-5.9.1-1.cdh5.9.1.p0.4/lib/hue/desktop/core/src/desktop/manage_entry.py", line 59, in entry
    execute_from_command_line(sys.argv)
  File "/opt/cloudera/parcels/CDH-5.9.1-1.cdh5.9.1.p0.4/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/opt/cloudera/parcels/CDH-5.9.1-1.cdh5.9.1.p0.4/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/cloudera/parcels/CDH-5.9.1-1.cdh5.9.1.p0.4/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/opt/cloudera/parcels/CDH-5.9.1-1.cdh5.9.1.p0.4/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/opt/cloudera/parcels/CDH-5.9.1-1.cdh5.9.1.p0.4/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/opt/cloudera/parcels/CDH-5.9.1-1.cdh5.9.1.p0.4/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/cloudera/parcels/CDH-5.9.1-1.cdh5.9.1.p0.4/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/cloudera/parcels/CDH-5.9.1-1.cdh5.9.1.p0.4/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/opt/cloudera/parcels/CDH-5.9.1-1.cdh5.9.1.p0.4/lib/hue/desktop/core/src/desktop/settings.py", line 323, in <module>
    "PASSWORD" : desktop.conf.get_database_password(),
  File "/opt/cloudera/parcels/CDH-5.9.1-1.cdh5.9.1.p0.4/lib/hue/desktop/core/src/desktop/conf.py", line 1353, in get_database_password
    password = DATABASE.PASSWORD_SCRIPT.get()
  File "/opt/cloudera/parcels/CDH-5.9.1-1.cdh5.9.1.p0.4/lib/hue/desktop/core/src/desktop/lib/conf.py", line 147, in get
    return self.config.get_value(data, present=present, prefix=self.prefix, coerce_type=True)
  File "/opt/cloudera/parcels/CDH-5.9.1-1.cdh5.9.1.p0.4/lib/hue/desktop/core/src/desktop/lib/conf.py", line 263, in get_value
    return self._coerce_type(raw_val, prefix)
  File "/opt/cloudera/parcels/CDH-5.9.1-1.cdh5.9.1.p0.4/lib/hue/desktop/core/src/desktop/lib/conf.py", line 283, in _coerce_type
    return self.type(raw)
  File "/opt/cloudera/parcels/CDH-5.9.1-1.cdh5.9.1.p0.4/lib/hue/desktop/core/src/desktop/lib/conf.py", line 714, in coerce_password_from_script
    raise subprocess.CalledProcessError(p.returncode, script)
subprocess.CalledProcessError: Command '/var/run/cloudera-scm-agent/process/720-hue-HUE_SERVER/altscript.sh sec-5-password' returned non-zero exit status 1</pre>

Export some env variables to bypass:
<code>export HUE_IGNORE_PASSWORD_SCRIPT_ERRORS=1
export HUE_DATABASE_PASSWORD=123456</code>
Script still reports 
<pre>Error: Password not present</pre>
But it can finish.

**Comment by mfernest** [comment]
Another student had a different complaint which I believe was caused by leaving `sudo` in the command line before the environment parameters. I can imagine similar errors if the user is not accustomed to setting parameters inline before a command. There are some syntax issues that must be worked out.
